import {
  PROJECT_ROLE_COPILOT,
  PROJECT_ROLE_MANAGER,
  PROJECT_ROLE_ACCOUNT_MANAGER,
  ROLE_ADMINISTRATOR,
  ROLE_CONNECT_ADMIN,
  ROLE_CONNECT_MANAGER,
  ROLE_CONNECT_ACCOUNT_MANAGER
} from './constants'

export default {
  EDIT_PROJECT_PLAN: {
    projectRoles: [PROJECT_ROLE_MANAGER, PROJECT_ROLE_COPILOT, ROLE_CONNECT_ADMIN],
    topcoderRoles: [ROLE_ADMINISTRATOR, ROLE_CONNECT_ADMIN],
  },
  INVITE_TOPCODER_MEMBER: {
    projectRoles: [PROJECT_ROLE_MANAGER, PROJECT_ROLE_ACCOUNT_MANAGER, ROLE_CONNECT_ADMIN],
    topcoderRoles: [ROLE_ADMINISTRATOR, ROLE_CONNECT_ADMIN, ROLE_CONNECT_MANAGER, ROLE_CONNECT_ACCOUNT_MANAGER],
  },
  ACCESS_PRIVATE_POST: {
    topcoderRoles: [PROJECT_ROLE_COPILOT, ROLE_CONNECT_MANAGER, ROLE_CONNECT_ADMIN, ROLE_ADMINISTRATOR]
  }
}
