import {PROJECT_ROLE_COPILOT, PROJECT_ROLE_MANAGER, ROLE_ADMINISTRATOR, ROLE_CONNECT_ADMIN} from './constants'

export default {
  EDIT_PROJECT_PLAN: {
    projectRoles: [PROJECT_ROLE_MANAGER, PROJECT_ROLE_COPILOT, ROLE_CONNECT_ADMIN],
    topcoderRoles: [ROLE_ADMINISTRATOR, ROLE_CONNECT_ADMIN],
  }
}
